services:
  - type: web
    name: christmas-countdown-2025
    runtime: go
    region: oregon
    plan: free
    buildCommand: go build -ldflags "-s -w" -o bin/app main.go
    startCommand: ./bin/app
    envVars:
      - key: PORT
        value: 10000
      - key: GO_ENV
        value: production
    healthCheckPath: /health
